# Generated by Django 3.0.8 on 2020-09-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200905_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
