# Generated by Django 3.0.8 on 2020-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200911_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='profile',
            name='date_posted',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
